name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# Include all changes, not just PRs
include-pre-releases: false
commitish: master

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🧹 Maintenance'
    labels:
      - 'maintenance'
      - 'chore'
      - 'dependencies'
  - title: '⚠️ Breaking Changes'
    labels:
      - 'breaking-change'

change-template: '- $TITLE @$AUTHOR'
no-changes-template: '- No changes'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking-change'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'fix'
      - 'documentation'
      - 'chore'
      - 'maintenance'
  default: patch

template: |
  ## What's Changed

  $CHANGES

  ## New Contributors
  $CONTRIBUTORS

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

exclude-labels:
  - 'skip-changelog'
  - 'duplicate'
  - 'question'
  - 'invalid'
  - 'wontfix'

# Enhanced autolabeler for conventional commits  
autolabeler:
  - label: 'feature'
    title:
      - '/^feat(\(.+\))?\!?:/i'
  - label: 'bug'
    title:
      - '/^fix(\(.+\))?\!?:/i'
  - label: 'documentation'
    title:
      - '/^docs(\(.+\))?\!?:/i'
    files:
      - '*.md'
      - 'docs/**'
  - label: 'chore'
    title:
      - '/^chore(\(.+\))?\!?:/i'
      - '/^ci(\(.+\))?\!?:/i'
      - '/^build(\(.+\))?\!?:/i'
      - '/^refactor(\(.+\))?\!?:/i'
  - label: 'breaking-change'
    title:
      - '/^.*\!:/i'

# Replacers to clean up commit messages
replacers:
  - search: '/^(feat|fix|docs|chore|ci|build|refactor)(\(.+\))?\!?:\s*/i'
    replace: ''
