name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# Configuration for PR-based workflow
include-pre-releases: false
commitish: master

# Filter out bots from contributor lists  
exclude-contributors:
  - 'dependabot[bot]'
  - 'github-actions[bot]'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
    collapse-after: 3
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
    collapse-after: 3
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
    collapse-after: 3
  - title: '🧹 Maintenance'
    labels:
      - 'maintenance'
      - 'chore'
      - 'dependencies'
    collapse-after: 3
  - title: '⚠️ Breaking Changes'
    labels:
      - 'breaking-change'

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
no-changes-template: '- No changes'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking-change'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'fix'
      - 'documentation'
      - 'chore'
      - 'maintenance'
  default: patch

template: |
  ## What's Changed

  $CHANGES
  
  ## Thanks ❤️
  $CONTRIBUTORS
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

exclude-labels:
  - 'skip-changelog'
  - 'duplicate'
  - 'question'
  - 'invalid'
  - 'wontfix'

# Enhanced autolabeler for conventional commits and files
autolabeler:
  - label: 'feature'
    title:
      - '/^feat(\(.+\))?\!?:/i'
      - '/^Feature:/i'
    branch:
      - '/^feature\/.+/'
      - '/^feat\/.+/'
  - label: 'bug'
    title:
      - '/^fix(\(.+\))?\!?:/i'
      - '/^Fix:/i'
      - '/^Bug:/i'
    branch:
      - '/^fix\/.+/'
      - '/^bug\/.+/'
      - '/^hotfix\/.+/'
  - label: 'documentation'
    title:
      - '/^docs(\(.+\))?\!?:/i'
      - '/^Documentation:/i'
    files:
      - '*.md'
      - 'docs/**/*'
      - '.github/**/*'
    branch:
      - '/^docs\/.+/'
  - label: 'chore'
    title:
      - '/^chore(\(.+\))?\!?:/i'
      - '/^ci(\(.+\))?\!?:/i'
      - '/^build(\(.+\))?\!?:/i'
      - '/^refactor(\(.+\))?\!?:/i'
      - '/^Chore:/i'
    files:
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**/*'
      - '.gitignore'
      - 'tsconfig.json'
      - 'biome.json'
    branch:
      - '/^chore\/.+/'
      - '/^refactor\/.+/'
  - label: 'dependencies'
    title:
      - '/^(chore|build)(\(.+\))?\!?:\s*(bump|update|upgrade)/i'
    files:
      - 'package.json'
      - 'package-lock.json'
  - label: 'breaking-change'
    title:
      - '/^.*\!:/i'
      - '/^BREAKING CHANGE:/i'

# Replacers to clean up commit messages in release notes
replacers:
  - search: '/^(feat|fix|docs|chore|ci|build|refactor)(\(.+\))?\!?:\s*/i'
    replace: ''
  - search: '/^(Feature|Fix|Bug|Documentation|Chore):\s*/i'
    replace: ''
