name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

include-pre-releases: true
commitish: master

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🧹 Maintenance'
    labels:
      - 'maintenance'
      - 'chore'
      - 'dependencies'
  - title: '⚠️ Breaking Changes'
    labels:
      - 'breaking-change'

change-template: '- $TITLE (#$NUMBER)'
no-changes-template: '- No changes yet'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking-change'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'fix'
      - 'documentation'
      - 'chore'
      - 'maintenance'
  default: patch

template: |
  ## Changes

  $CHANGES

  ## Contributors

  Thanks to all contributors who made this release possible!

exclude-labels:
  - 'skip-changelog'
  - 'duplicate'
  - 'question'
  - 'invalid'
  - 'wontfix'

autolabeler:
  - label: 'feature'
    title:
      - '/^feat(\(.+\))?\!?:.+$/i'
  - label: 'bug'
    title:
      - '/^fix(\(.+\))?\!?:.+$/i'
  - label: 'documentation'
    title:
      - '/^docs(\(.+\))?\!?:.+$/i'
    files:
      - '*.md'
      - 'docs/**'
  - label: 'chore'
    title:
      - '/^chore(\(.+\))?\!?:.+$/i'
      - '/^ci(\(.+\))?\!?:.+$/i'
      - '/^build(\(.+\))?\!?:.+$/i'
      - '/^refactor(\(.+\))?\!?:.+$/i'
  - label: 'breaking-change'
    title:
      - '/^.+\!:.+$/i'
