name: Branch Protection & PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Lint and validate PR title
  pr_validation:
    name: PR Validation
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (newline-delimited).
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          # Configure which scopes are allowed (newline-delimited).
          # These are optional and can be omitted.
          scopes: |
            cli
            commands
            docs
            ci
            deps
          # Configure that a scope is required.
          requireScope: false
          # Configure additional validation for the subject based on a regex.
          # This example ensures the subject doesn't start with an uppercase character.
          subjectPattern: ^(?![A-Z]).+$
          # If you use GitHub Enterprise, you can set this to the URL of your server
          # githubBaseUrl: https://github.myorg.com/api/v3
          # Configure additional validation for the subject based on a regex.
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.

  # Check for required files and structure
  project_structure:
    name: Project Structure Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check required files
        run: |
          echo "Checking for required files..."
          
          required_files=(
            "package.json"
            "README.md"
            "CHANGELOG.md"
            "LICENSE"
            "CONTRIBUTING.md"
            ".github/workflows/release.yml"
            ".github/release-drafter.yml"
          )
          
          missing_files=()
          
          for file in "${required_files[@]}"; do
            if [[ ! -f "$file" ]]; then
              missing_files+=("$file")
            fi
          done
          
          if [[ ${#missing_files[@]} -gt 0 ]]; then
            echo "❌ Missing required files:"
            printf '%s\n' "${missing_files[@]}"
            exit 1
          else
            echo "✅ All required files are present"
          fi

  # Add a label based on PR size
  pr_size_labeler:
    name: PR Size Labeler
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Label PR based on size
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: '10'
          s_label: 'size/S'
          s_max_size: '100'
          m_label: 'size/M'
          m_max_size: '500'
          l_label: 'size/L'
          l_max_size: '1000'
          xl_label: 'size/XL'
          fail_if_xl: 'false'
