name: Release & Publish

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - dev
  release:
    types: [published]

jobs:
  # Build and test the project for all PRs and pushes
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  # Update release draft when changes are pushed to master
  update_release_draft:
    name: Update Release Draft
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Publish to npm when release is published
  publish_to_npm:
    name: Publish to npm
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.repository.default_branch }}      
      - name: Set up Node.js for publishing
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update package.json and CHANGELOG with standard-version
        run: |
          # Extract version from release tag
          RELEASE_VERSION="${{ github.event.release.tag_name }}"
          VERSION_WITHOUT_V=$(echo $RELEASE_VERSION | sed 's/^v//')
          
          echo "Release version: $RELEASE_VERSION"
          echo "Version without v: $VERSION_WITHOUT_V"
          
          # Run standard-version to update package.json and CHANGELOG.md
          npx standard-version --release-as $VERSION_WITHOUT_V --skip.tag
          
          # Push changes back to the current branch
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $CURRENT_BRANCH"
          git push origin $CURRENT_BRANCH

      - name: Build project
        run: npm run build

      - name: Verify version consistency
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          GIT_TAG_VERSION=${{ github.event.release.tag_name }}
          GIT_TAG_VERSION_STRIPPED=$(echo $GIT_TAG_VERSION | sed 's/^v//')

          echo "Package.json version: $PKG_VERSION"
          echo "GitHub release tag: $GIT_TAG_VERSION (stripped: $GIT_TAG_VERSION_STRIPPED)"

          if [ "$PKG_VERSION" != "$GIT_TAG_VERSION_STRIPPED" ]; then
            echo "Error: package.json version ($PKG_VERSION) does not match git tag version ($GIT_TAG_VERSION_STRIPPED)."
            exit 1
          fi

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}